### PR TITLE
Secret can be with or w/o new-line character

### PR DESCRIPTION
**Pull request by mitchvdl**
As per: https://github.com/all-ride/ride-lib-varnish/issues/2

### CODE REVIEW

**Comment by ride-user** [comment]
@mitchvdl Thanks for your pull request. I checked the documentation of Varnish and you are right. It states there is no need of a new-line between the contents of the secret file and the challenge.

However, I have problems connecting when I apply your pull request. Your secret, does it come from a file_get_contents call or is it a controlled parameter string? The reason I ask is because text files should have a new-line character at the end and the documentation states "the contents of the secret file". So for me, that means, including a new-line. 

If this would be the case, I could add a check on the new-line character and omit it when it's in the secret string instead of always omitting it.

**Comment by ride-user** [comment]
I tested with Varnish 3 and 4 btw.

**Comment by mitchvdl** [comment]
How I understand the class it is regardless of how you obtain the secret
(by input field, reading from a file etc, static variable) the hash should
be generated according to the Varnish requirement.

The developer implementing it should provide the secret in the correct value

Yours sincerely,  mit freundlichen Grüßen, Met vriendelijke groet

Ing. Mitch Vanderlinden
Applied Computer Science

e | info@mitchvdl.be
w | www.mitchvdl.be

**Comment by mitchvdl** [comment]
- I use this in combination with Magento's EcomDev - Varnish module which
  basically already has the option to add a new line or not (by configuration)

Yours sincerely,  mit freundlichen Grüßen, Met vriendelijke groet

Ing. Mitch Vanderlinden
Applied Computer Science

e | info@mitchvdl.be
w | www.mitchvdl.be

**Comment by ride-user** [comment]
Oke, I took a deeper look and you are right. All the secret files I use have a trailing \n but I don't add them to my secret parameter value. I updated the documentation and released as 1.0.1

**Pull request merged**
